# Generated by Django 4.0 on 2023-09-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='field_name',
            field=models.CharField(default='image', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
